hello-world-data/config/routes.rb
Rails.application.routes.draw do
  root 'hello#data'
  resources :greetings
end

hello-world-data/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hello-world-data/app/models/greeting.rb
class Greeting < ApplicationRecord
end

hello-world-data/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

hello-world-data/app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  before_action :set_greeting, only: [:show, :edit, :update, :destroy]

  # GET /greetings
  # GET /greetings.json
  def index
    @greetings = Greeting.all
  end

  # GET /greetings/1
  # GET /greetings/1.json
  def show
  end

  # GET /greetings/new
  def new
    @greeting = Greeting.new
  end

  # GET /greetings/1/edit
  def edit
  end

  # POST /greetings
  # POST /greetings.json
  def create
    @greeting = Greeting.new(greeting_params)

    respond_to do |format|
      if @greeting.save
        format.html { redirect_to @greeting, notice: 'Greeting was successfully created.' }
        format.json { render :show, status: :created, location: @greeting }
      else
        format.html { render :new }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /greetings/1
  # PATCH/PUT /greetings/1.json
  def update
    respond_to do |format|
      if @greeting.update(greeting_params)
        format.html { redirect_to @greeting, notice: 'Greeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @greeting }
      else
        format.html { render :edit }
        format.json { render json: @greeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /greetings/1
  # DELETE /greetings/1.json
  def destroy
    @greeting.destroy
    respond_to do |format|
      format.html { redirect_to greetings_url, notice: 'Greeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_greeting
      @greeting = Greeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def greeting_params
      params.require(:greeting).permit(:language, :content)
    end
end

hello-world-data/app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def data
  end
end

hello-world-data/app/helpers/application_helper.rb
module ApplicationHelper
end

hello-world-data/app/helpers/greetings_helper.rb
module GreetingsHelper
end

hello-world-data/app/helpers/hello_helper.rb
module HelloHelper
end

hello-world-data/app/views/greetings/_form.html.erb
<%= form_with(model: greeting, local: true) do |form| %>
  <% if greeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hello-world-data/app/views/greetings/edit.html.erb
<h1>Editing Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Show', @greeting %> |
<%= link_to 'Back', greetings_path %>

hello-world-data/app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Greetings</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @greetings.each do |greeting| %>
      <tr>
        <td><%= greeting.language %></td>
        <td><%= greeting.content %></td>
        <td><%= link_to 'Show', greeting %></td>
        <td><%= link_to 'Edit', edit_greeting_path(greeting) %></td>
        <td><%= link_to 'Destroy', greeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Greeting', new_greeting_path %>

hello-world-data/app/views/greetings/new.html.erb
<h1>New Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Back', greetings_path %>

hello-world-data/app/views/greetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @greeting.language %>
</p>

<p>
  <strong>Content:</strong>
  <%= @greeting.content %>
</p>

<%= link_to 'Edit', edit_greeting_path(@greeting) %> |
<%= link_to 'Back', greetings_path %>

hello-world-data/app/views/hello/data.html.erb
<div id="root"></div>

hello-world-data/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorldData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>